environment = "dev"
instance_type = "t3.micro"
vpc_cidr = "10.0.0.0/16"
project_name = "terraform-test"
aws_region = "us-east-1"
github_org = "rodgerema"
github_repo = "terraform-test"
terraform_state_bucket = "terraform-backend-087952009579"